Added gun hit events & update translation.
nexusnode/crafting-dead pull request #101
Opened 2021-03-14 04:25 UTC by Liangbai2333

Added gun hit block event and hit entity event.

2021-03-14 12:25 UTC, TSaltedfishKing commented
![H1PBE{QP7POHDP@_EL4HYCY](https://user-images.githubusercontent.com/60768370/111068342-61f87100-8503-11eb-88df-9d330342d7fd.jpg)
是大佬

2021-03-14 15:36 UTC, Sm0keySa1m0n requested changes

2021-03-14 15:36 UTC, Sm0keySa1m0n commented on crafting-dead-core/src/main/java/com/craftingdead/core/capability/gun/GunImpl.java
> +    if (event.isCanceled()) {
This can be performed on the post method.

2021-03-14 15:36 UTC, Sm0keySa1m0n commented on crafting-dead-core/src/main/java/com/craftingdead/core/capability/gun/GunImpl.java
> +    if (event.isCanceled()) {
This can be performed on the post method.

2021-03-28 04:21 UTC, Liangbai2333 commented
Could you check it?

2021-03-28 10:55 UTC, merged